OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Models/Cake.cs
// <copyright file="Cake.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace MyCakeShop.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Cake class.
    /// </summary>
    public class Cake
    {
        /// <summary>
        /// Gets or sets property. The ID of the cake.
        /// </summary>
        [Display(Name = "Cake id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets cake name.
        /// </summary>
        [Display(Name = "Cake name")]
        [Required]
        [StringLength(30, MinimumLength = 3)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets property. The type of cake.
        /// </summary>
        [Display(Name = "Cake type")]
        [Required]
        [StringLength(30, MinimumLength = 3)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets property. The date the cake was made.
        /// </summary>
        [Display(Name = "Cake making date")]
        [Required]
        public DateTime MadeDate { get; set; }

        /// <summary>
        /// Gets or sets property. The expiration date of the cake.
        /// </summary>
        [Display(Name = "Cake expiration date")]
        [Required]
        public DateTime ExpirationDate { get; set; }

        /// <summary>
        /// Gets or sets property. The price of the cake in HUF per piece.
        /// </summary>
        [Display(Name = "Cake price")]
        [Required]
        public int Price { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether gets or sets property. This cake lactose free.
        /// </summary>
        [Display(Name = "Cake is lactose free")]
        [Required]
        public bool LactoseFree { get; set; }

        /// <summary>
        /// Gets or sets property. How popular the particular cake is among consumers.
        /// </summary>
        [Display(Name = "Cake popularity")]
        [Required]
        [Range(1, 5)]
        public int Popularity { get; set; }

        /// <summary>
        /// Gets or sets property. The ID of the maker of the cake.
        /// </summary>
        [Display(Name = "Cake maker id")]
        [Required]
        public int MakerId { get; set; }
    }
}

OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Controllers/CakesController.cs
// <copyright file="CakesController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace MyCakeShop.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using MyCakeShop.Logic;
    using MyCakeShop.Web.Models;

    /// <summary>
    /// Cake controller.
    /// </summary>
    public class CakesController : Controller
    {
        private IStockLogic logic;
        private IMapper mapper;
        private CakeListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="CakesController"/> class.
        /// </summary>
        /// <param name="logic">Cake logic.</param>
        /// <param name="mapper">Mapper.</param>
        public CakesController(IStockLogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new CakeListViewModel();
            this.vm.EditedCake = new Models.Cake();
            if (logic != null && mapper != null)
            {
                var cakes = logic.GetAllCakes();
                this.vm.ListOfCakes = mapper.Map<IList<Data.Cake>, List<Models.Cake>>(cakes);
            }
        }

        /// <summary>
        /// Index.
        /// </summary>
        /// <returns>Action result.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("CakesIndex", this.vm);
        }

        /// <summary>
        /// Details.
        /// </summary>
        /// <param name="id">Cake id.</param>
        /// <returns>Action result.</returns>
        public IActionResult Details(int id)
        {
            return this.View("CakesDetails", this.GetCakeModel(id));
        }

        /// <summary>
        /// Remove.
        /// </summary>
        /// <param name="id">Cake id.</param>
        /// <returns>Action result.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete FAIL";
            if (this.logic.RemoveCake(id))
            {
                this.TempData["editResult"] = "Delete OK";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Add.
        /// </summary>
        /// <returns>Action result.</returns>
        public IActionResult Add()
        {
            this.ViewData["editAction"] = "AddNew";
            Models.CakeListViewModel vm = new Models.CakeListViewModel();
            vm.ListOfCakes = MyCakeShop.Web.Models.MapperFactory.ConvertToWebCakes(this.logic.GetAllCakes().ToList());
            vm.EditedCake = new Models.Cake();

            return this.View("CakesEdit2", vm);
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="id">Cake id.</param>
        /// <returns>Action result.</returns>
        public IActionResult Edit(int id)
        {
            Models.CakeListViewModel vm = new Models.CakeListViewModel();
            this.ViewData["editAction"] = "Edit";
            vm.EditedCake = this.GetCakeModel(id);
            return this.View("CakesEdit", vm);
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="vm">View Model.</param>
        /// <param name="editAction">Edit action.</param>
        /// <returns>Action result.</returns>
        [HttpPost]
        public IActionResult Edit(Models.CakeListViewModel vm, string editAction)
        {
            if (vm.EditedCake != null)
            {
                var cake = vm.EditedCake;
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.logic.InsertCake(cake.Name, cake.Type, cake.MadeDate, cake.ExpirationDate, cake.Price, cake.LactoseFree, cake.Popularity, cake.MakerId);
                        this.TempData["editResult"] = "The addition was successful";
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "The addition failed: " + ex.Message;
                    }
                }
                else
                {
                    if (this.logic.ChangePrice(cake.Id, cake.Price) && this.logic.ChangePopularity(cake.Id, cake.Popularity) && this.logic.ChangeExpirationDate(cake.Id, cake.ExpirationDate))
                    {
                        this.TempData["editResult"] = "The change was successful";
                    }
                    else
                    {
                        this.TempData["editResult"] = "The change failed";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                if (vm != null)
                {
                    this.ViewData["editAction"] = "Edit";
                    vm.EditedCake = vm.EditedCake;
                    return this.View("CakesEdit", vm);
                }
                else
                {
                    return null;
                }
            }
        }

        private Models.Cake GetCakeModel(int id)
        {
            Data.Cake oneCake = this.logic.GetOneCake(id);
            return this.mapper.Map<Data.Cake, Models.Cake>(oneCake);
        }
    }
}

OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Views/Cakes/CakesDetails.cshtml
@model MyCakeShop.Web.Models.Cake

@{
    ViewData["Title"] = "CakesDetails";
}

<h2>The details of the cake</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MadeDate)</td>
        <td>@Html.DisplayFor(m => m.MadeDate)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ExpirationDate)</td>
        <td>@Html.DisplayFor(m => m.ExpirationDate)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.LactoseFree)</td>
        <td>@Html.DisplayFor(m => m.LactoseFree)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Popularity)</td>
        <td>@Html.DisplayFor(m => m.Popularity)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.MakerId)</td>
        <td>@Html.DisplayFor(m => m.MakerId)</td>
    </tr>
</table>

OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Views/Cakes/CakesEdit.cshtml
@model MyCakeShop.Web.Models.CakeListViewModel

<h2>Change cake details</h2>

@using (Html.BeginForm("Edit", "Cakes"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.EditedCake.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    @*<div class="editor-label">@Html.LabelFor(m => m.EditedCake.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Type)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.MadeDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.MadeDate)</div>*@

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.ExpirationDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.ExpirationDate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Price)</div>

    @*<div class="editor-label">@Html.LabelFor(m => m.EditedCake.LactoseFree)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.LactoseFree)</div>*@

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Popularity)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Popularity)</div>

    @*<div class="editor-label">@Html.LabelFor(m => m.EditedCake.MakerId)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.MakerId)</div>*@

    <input type="submit" value="SEND" />
}

OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Views/Cakes/CakesEdit2.cshtml
@model MyCakeShop.Web.Models.CakeListViewModel

<h2>Change cake details</h2>

@using (Html.BeginForm("Edit", "Cakes"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.EditedCake.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Type)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.MadeDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.MadeDate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.ExpirationDate)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.ExpirationDate)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Price)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.LactoseFree)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.LactoseFree)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.Popularity)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.Popularity)</div>

    <div class="editor-label">@Html.LabelFor(m => m.EditedCake.MakerId)</div>
    <div class="editor-field">@Html.EditorFor(m => m.EditedCake.MakerId)</div>

    <input type="submit" value="SEND" />
}

OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Views/Cakes/CakesIndex.cshtml
@model MyCakeShop.Web.Models.CakeListViewModel

@{
    ViewData["Title"] = "Crud Index";
}

<h2>CakeShop database</h2><b/>

@*<p style="color:red">
    @TempData["editResult"]
</p>*@

@*@await Html.PartialAsync("CakesEdit", Model.EditedCake)*@

@await Html.PartialAsync("CakesList", Model.ListOfCakes)

OENIK_PROG4HF_2021_1_KU9FUX/MyCakeShop.Web/Views/Cakes/CakesList.cshtml
@model IEnumerable<MyCakeShop.Web.Models.Cake>

<h2>List of all cakes</h2>
@TempData["editResult"]
@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Type)</th>
            <th>@Html.DisplayNameFor(m => m.First().ExpirationDate)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Modify</th>
        </tr>
        @foreach (var cake in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => cake.Name)</td>
                <td>@Html.DisplayFor(m => cake.Type)</td>
                <td>@Html.DisplayFor(m => cake.ExpirationDate)</td>
                <td>@Html.ActionLink("[Details]", "Details", new { id = cake.Id })</td>
                <td>@Html.ActionLink("[Delete]", "Remove", new { id = cake.Id })</td>
                <td>@Html.ActionLink("[Editing]", "Edit", new { id = cake.Id })</td>
            </tr>
        }
    </table>
}
@Html.ActionLink("Add new cake", "Add")